### ISSUE TITLE
文章內會出現日文亂碼

### ISSUE THREAD

**Issue by Aisuzuka** [Dothion/esjspy#1]
取得這一篇(https://www.esjzone.cc/detail/1544163514.html)文章時,
部分中文會變成無文法結構可言的日文

![圖片](https://user-images.githubusercontent.com/13333257/66841006-89a87a00-ef9b-11e9-985b-4c1faead5e25.png)

**Comment by mk2016a** [comment]
这个小说网站显示的内容包含日文原文罢了。

**Comment by Dothion** [comment]
不太清楚，这边没有复现成功

**Comment by Dothion** [comment]
找到问题了，是抗爬虫的原因
正在修复

**Comment by mk2016a** [comment]
我这里无法下载图片，是因为反爬虫的原因。简体中文和日文是正常显示的。请教遇到这套反爬虫系统，如何正常的下载图片？

**Comment by kutao207** [comment]
看了下网页源代码，所有带<p class="t"></p> tag的文本都是日文乱码，必须再向服务器请求一次才能得到正确的中文文本，用Python简单按JinJing.js的解码逻辑写了下，可以得到乱码的中文

`
import requests
from bs4 import BeautifulSoup

def decode_request(url, token):
    data = 'plxf=getTranslation&plxa[]=' + token
    headers = {"Method":"POST " + url + " HTTP/1.1", "Content-Type":"application/x-www-form-urlencoded", "Accept":"text/javascript, text/html, application/xml, text/xml, */*"}
    response = requests.post(url, data=data, headers=headers).content

    res = response.decode('unicode-escape').split('<JinJing>')[1].split('<')[0]   
    exec('global a; a='+res)
    global a     
    return a

with requests.Session() as s:    
    url = 'https://www.esjzone.cc/forum/1544163514/2349.html'
    html = s.get(url)
    soup = BeautifulSoup(html.content, 'lxml')

    token = soup.select("body > script")[0].text.split("'")[1]  # 获取getTranslation的第一个参数

    decoded_chinese = decode_request(url, token)  # 根据token伪造向url的请求获取<p class="t"></>内的正确文本
`

**Comment by s4028600** [comment]
> 看了下网页源代码，所有带`<p class="t"></p>` tag的文本都是日文乱码，必须再向服务器请求一次才能得到正确的中文文本，用Python简单按`JinJing.js`的解码逻辑写了下，可以解析乱码的中文
> 
> ```python
> import requests
> from bs4 import BeautifulSoup
> 
> def decode_request(url, token):
>     data = 'plxf=getTranslation&plxa[]=' + token
>     headers = {"Method":"POST " + url + " HTTP/1.1", "Content-Type":"application/x-www-form-urlencoded", "Accept":"text/javascript, text/html, application/xml, text/xml, */*"}
>     response = requests.post(url, data=data, headers=headers).content
>     res = response.decode('unicode-escape').split('<JinJing>')[1].split('<')[0]   
>     exec('global a; a='+res)
>     global a     
>     return a
> 
> with requests.Session() as s:    
>     url = 'https://www.esjzone.cc/forum/1544163514/2349.html'
>     html = s.get(url)
>     soup = BeautifulSoup(html.content, 'lxml')
>     token = soup.select("body > script")[0].text.split("'")[1]  # 获取getTranslation的第一个参数
> 
>     encoded_text = soup.select("p[class].t")
>     decoded_chinese = decode_request(url, token)  # 根据token伪造向url的请求获取<p class="t"></>内的正确文本
>     # 替换...
>     for e, d in zip(encoded_text, decoded_chinese):
>         e.string.replace_with(d)
> ```

有時候會出現
/storage/emulated/0/py/esj.py:9: DeprecationWarning: invalid escape sequence '\/'
  res = response.decode('unicode-escape').split('<JinJing>')[1].split('<')[0]

**Comment by mk2016a** [comment]
> decode('unicode-escape')

Try: decode('GBK') or UTF-8

**Comment by s4028600** [comment]
https://www.esjzone.cc/forum/1546106901/17713.html
    e.string.replace_with(d)
AttributeError: 'NoneType' object has no attribute 'replace_with'
推測是列表空值

**Comment by mk2016a** [comment]
> https://www.esjzone.cc/forum/1546106901/17713.html
> e.string.replace_with(d)
> AttributeError: 'NoneType' object has no attribute 'replace_with'
> 推測是列表空值

just write your own script

**Comment by s4028600** [comment]
是指自己編寫嗎
試過跳過e.string.replace_with(d)
但是字會擠在一起...

**Comment by s4028600** [comment]
https://www.esjzone.cc/forum/1546106901/17716.html
解決一個問題下一個馬上冒出來
這次完全無力了...
Traceback (most recent call last):
  File "D:\long\Desktop\esj.py", line 23, in <module>
    decoded_chinese = decode_request(url, token)  # 根据token伪造向url的请求获取<p class="t"></>内的正确文本
  File "D:\long\Desktop\esj.py", line 10, in decode_request
    exec('global a; a='+res)
  File "<string>", line 1
    global a; a=["&nbsp;
                       ^
SyntaxError: EOL while scanning string literal
